org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'messageSender'
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'messageSender' defined in class path resource [jnjgtb2boutboundservice-spring.xml]: Unsatisfied dependency expressed through constructor parameter 0: Could not convert argument value of type [org.apache.hc.client5.http.impl.classic.InternalHttpClient] to required type [org.apache.http.client.HttpClient]: Failed to convert value of type 'org.apache.hc.client5.http.impl.classic.InternalHttpClient' to required type 'org.apache.http.client.HttpClient'; Cannot convert value of type 'org.apache.hc.client5.http.impl.classic.InternalHttpClient' to required type 'org.apache.http.client.HttpClient': no matching editors or conversion strategy found