UnsatisfiedDependencyException: Error creating bean with name 'messageSender' defined in class
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webserviceTemplateForNfe' defined in class path resource [jnjb2boutboundservice-spring.xml]: Cannot resolve reference to bean 'messageSender' while setting bean property 'messageSender'
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:377) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:135) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1725) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1474) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:606) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:373) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.instantiateSingleton(DefaultListableBeanFactory.java:1221) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingleton(DefaultListableBeanFactory.java:1187) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:1123) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:987) ~[spring-context-6.2.11.jar:6.2.11]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627) ~[spring-context-6.2.11.jar:6.2.11]
	at de.hybris.platform.core.HybrisContextFactory.refreshContext(HybrisContextFactory.java:88) ~[coreserver.jar:?]
	at de.hybris.platform.core.HybrisContextFactory$ApplicationContextFactory.build(HybrisContextFactory.java:256) ~[coreserver.jar:?]
	at de.hybris.platform.core.HybrisContextHolder.getApplicationInstance(HybrisContextHolder.java:78) ~[coreserver.jar:?]
	at de.hybris.platform.core.AbstractTenant.createCoreApplicationContext(AbstractTenant.java:815) ~[coreserver.jar:?]
	at de.hybris.platform.core.AbstractTenant.doStartupSafe(AbstractTenant.java:856) ~[coreserver.jar:?]
	at de.hybris.platform.core.AbstractTenant.doStartUp(AbstractTenant.java:781) ~[coreserver.jar:?]
	at de.hybris.platform.core.Registry.assureTenantStarted(Registry.java:658) ~[coreserver.jar:?]
	at de.hybris.platform.core.Registry.activateTenant(Registry.java:719) ~[coreserver.jar:?]
	at de.hybris.platform.core.Registry.setCurrentTenant(Registry.java:568) ~[coreserver.jar:?]
	at de.hybris.platform.core.Registry.activateMasterTenant(Registry.java:627) ~[coreserver.jar:?]
	at de.hybris.platform.core.Registry.startup(Registry.java:441) ~[coreserver.jar:?]
	at de.hybris.platform.core.ClassLoaderUtils.executeWithWebClassLoaderParentIfNeeded(ClassLoaderUtils.java:35) ~[coreserver.jar:?]
	at de.hybris.platform.spring.HybrisContextLoaderListener.startRegistry(HybrisContextLoaderListener.java:353) ~[coreserver.jar:?]
	at de.hybris.platform.spring.HybrisContextLoaderListener.doInitWebApplicationContext(HybrisContextLoaderListener.java:213) ~[coreserver.jar:?]
	at de.hybris.platform.spring.HybrisContextLoaderListener.initWebApplicationContext(HybrisContextLoaderListener.java:200) ~[coreserver.jar:?]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:126) ~[spring-web-6.2.11.jar:6.2.11]
	at de.hybris.platform.spring.HybrisContextLoaderListener.contextInitializedInternal(HybrisContextLoaderListener.java:97) ~[coreserver.jar:?]
	at de.hybris.platform.spring.HybrisContextLoaderListener.contextInitialized(HybrisContextLoaderListener.java:92) ~[coreserver.jar:?]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4046) ~[catalina.jar:10.1.44]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4474) ~[catalina.jar:10.1.44]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) ~[catalina.jar:10.1.44]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203) ~[catalina.jar:10.1.44]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193) ~[catalina.jar:10.1.44]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-util.jar:10.1.44]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'messageSender' defined in class path resource [jnjgtb2boutboundservice-spring.xml]: Unsatisfied dependency expressed through constructor parameter 0: Could not convert argument value of type [org.apache.hc.client5.http.impl.classic.InternalHttpClient] to required type [org.apache.http.client.HttpClient]: Failed to convert value of type 'org.apache.hc.client5.http.impl.classic.InternalHttpClient' to required type 'org.apache.http.client.HttpClient'; Cannot convert value of type 'org.apache.hc.client5.http.impl.classic.InternalHttpClient' to required type 'org.apache.http.client.HttpClient': no matching editors or conversion strategy found
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:766) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:240) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1395) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:569) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.11.jar:6.2.11]